In [1]:
import pandas as pd
import matplotlib as plt

happiness = pd.read_csv("DataSets/2018-2019+Happiness.csv")
airbnb = pd.read_csv("DataSets/airbnb.csv")
sales = pd.read_csv("DataSets/web_sales.csv")
salaries = pd.read_csv("DataSets/salaries.csv")
eth = pd.read_csv("DataSets/Ethereum+Historical+Data.csv")

## tratamiento de valores nulos

In [2]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30478 entries, 0 to 30477
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Host Id                     30478 non-null  int64
 1   Host Since                  30475 non-null  object
 2   Name                        30478 non-null  object
 3   Neighbourhood               30478 non-null  object
 4   Property Type               30475 non-null  object
 5   Review Scores Rating (bin)  22155 non-null  float64
 6   Room Type                   30478 non-null  object
 7   Zipcode                     30344 non-null  float64
 8   Beds                        30393 non-null  float64
 9   Number of Records           30478 non-null  int64
 10  Number Of Reviews           30478 non-null  int64
 11  Price                       30478 non-null  int64
 12  Review Scores Rating        22155 non-null  float64
dtypes: float64(4), int64(4), object(5)
memory usage: 3.0+ MB

**Podemos identificar valores nulos con la funcion "isna()", la cual nos arrojara el dataframe con valores bool en cada espacio que tengqas valores nulos**
<br><br>
***Por ejemplo:***

In [3]:
airbnb.isna()

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,False,True,False,False,False,True,False,False,False,False,False,False,True
1,False,True,False,False,False,True,False,False,False,False,False,False,True
2,False,True,False,False,False,True,False,False,False,False,False,False,True
3,False,False,False,False,False,True,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,False,False,False,False,False,True,False,False,False,False,False,False,True
30474,False,False,False,False,False,True,False,False,False,False,False,False,True
30475,False,False,False,False,False,True,False,False,False,False,False,False,True
30476,False,False,False,False,False,True,False,False,False,False,False,False,True
30477,False,False,False,False,False,True,False,False,False,False,False,False,True

**Podemos contar los nulos utilizando la funcion "sum()" en conjunto con "isna()"** <br><br>

***Por ejemplo:***

In [4]:
airbnb.isna().sum() #sum va despues por logica, ya que isna identifica nulos y sum suma los resultados obtenidos

Host Id                          0
Host Since                       3
Name                             0
Neighbourhood                    0
Property Type                    3
Review Scores Rating (bin)    8323
Room Type                        0
Zipcode                        134
Beds                            85
Number of Records                0
Number Of Reviews                0
Price                            0
Review Scores Rating          8323
dtype: int64

Podemos ver que Host Since, Property Type, Review Scores Rating (bin), Zipcode y otras columnas tienen varios valores nulos, para el ejemplo usaremos Review Scores Rating

In [5]:
airbnb['Review Scores Rating']

0         NaN
1         NaN
2         NaN
3         NaN
4        96.0
         ...
30473     NaN
30474     NaN
30475     NaN
30476     NaN
30477     NaN
Name: Review Scores Rating, Length: 30478, dtype: float64

In [6]:
airbnb['Review Scores Rating'].isna() 
#isna() tambien se puede usar para columnas especificas como aqui, lo que nos mostrara solo los resultados con NaN en la columna consultada

0         True
1         True
2         True
3         True
4        False
         ...
30473     True
30474     True
30475     True
30476     True
30477     True
Name: Review Scores Rating, Length: 30478, dtype: bool

In [7]:
airbnb[airbnb['Review Scores Rating'].isna()] 
#Podemos ver de forma mas ordenada estos resultados adicionando otra vez el nombre del dataframe y corchetes

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,26/06/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
13,2787,7/09/2008,Renovated and spacious townhome,Brooklyn,House,NaN,Private room,11223.0,1.0,1,0,68,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,43022976,31/08/2015,10 Mins to Time Square/two floors,Queens,Apartment,NaN,Entire home/apt,11101.0,5.0,1,0,300,NaN
30474,42993382,31/08/2015,"1BR ocean view & F,Q train st",Brooklyn,Apartment,NaN,Private room,11224.0,2.0,1,0,125,NaN
30475,43033067,31/08/2015,Amazing Private Room,Brooklyn,Other,NaN,Private room,11206.0,1.0,1,0,80,NaN
30476,43000991,31/08/2015,Charming private female room: UWS,Manhattan,Apartment,NaN,Private room,10025.0,1.0,1,0,35,NaN
30477,42999189,31/08/2015,Huge Beautiful Bedroom - Astoria,Queens,House,NaN,Private room,11105.0,1.0,1,0,80,NaN

**Para mas comodidad, podemos poner en una variable solamente los registros con valores NaN en review score rating**

In [8]:
airbnb_no_reviews = airbnb[airbnb['Review Scores Rating'].isna()]

In [9]:
airbnb_no_reviews

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,26/06/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
13,2787,7/09/2008,Renovated and spacious townhome,Brooklyn,House,NaN,Private room,11223.0,1.0,1,0,68,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,43022976,31/08/2015,10 Mins to Time Square/two floors,Queens,Apartment,NaN,Entire home/apt,11101.0,5.0,1,0,300,NaN
30474,42993382,31/08/2015,"1BR ocean view & F,Q train st",Brooklyn,Apartment,NaN,Private room,11224.0,2.0,1,0,125,NaN
30475,43033067,31/08/2015,Amazing Private Room,Brooklyn,Other,NaN,Private room,11206.0,1.0,1,0,80,NaN
30476,43000991,31/08/2015,Charming private female room: UWS,Manhattan,Apartment,NaN,Private room,10025.0,1.0,1,0,35,NaN
30477,42999189,31/08/2015,Huge Beautiful Bedroom - Astoria,Queens,House,NaN,Private room,11105.0,1.0,1,0,80,NaN

**Digamos que ahora quiero ver los registros que no tienen NaN en la columna de reviews. Esto lo podemos hacer con la funcion "notna()"**

In [10]:
airbnb_with_reviews = airbnb[airbnb['Review Scores Rating'].notna()]

In [11]:
airbnb_with_reviews

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
4,500,26/06/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0
5,1039,25/07/2008,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0
6,1783,12/08/2008,Amazing Also,Manhattan,Apartment,100.0,Entire home/apt,10004.0,1.0,1,9,250,100.0
7,2078,15/08/2008,"Colorful, quiet, & near the subway!",Brooklyn,Apartment,90.0,Private room,11201.0,1.0,1,80,90,94.0
8,2339,20/08/2008,East Village Cocoon: 2 Bedroom Flat,Manhattan,Apartment,90.0,Entire home/apt,10009.0,2.0,1,95,270,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30332,42349033,24/08/2015,Cute cozy studio in east village,Manhattan,Apartment,100.0,Entire home/apt,10003.0,1.0,1,1,90,100.0
30347,42430249,24/08/2015,Room in new spacious loft!,Brooklyn,Apartment,80.0,Private room,11222.0,1.0,1,1,65,80.0
30378,42518458,25/08/2015,Williamsburg Luxury Loft!??Bed Top,Brooklyn,Loft,100.0,Shared room,11206.0,1.0,1,1,55,100.0
30404,42697124,27/08/2015,"Cute, Clean Room- East Williamsburg",Brooklyn,Apartment,100.0,Private room,11206.0,1.0,1,1,60,100.0
30409,42726605,27/08/2015,Cozy and Near Tourist Attractions,Manhattan,Apartment,80.0,Private room,10002.0,1.0,1,1,99,80.0

**Asi como vimos y guardamos en variables los Nulos y no nulos, podemos tambien borrar los registros que tengan valores nulos con la funcion "dropna()", ya sea de todo el dataframe, o especificando columna en la que debe estar el NaN para ser borrado el registro (esto ultimo lo hacemos dandole a dropna(), el parametro subset junto a la columna a tomar en cuenta)**<br><br>

***Por ejemplo: Para borrar todos los registros con un valor en NaN y guardar el resultado en una variable, se hace de la siguioente forma:***

In [12]:
airbnb_no_null = airbnb.dropna() 
#esta funcion borrara todos los registros que tengan NaN, sea en la columna que sea

In [13]:
airbnb_no_null

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
4,500,26/06/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0
5,1039,25/07/2008,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0
6,1783,12/08/2008,Amazing Also,Manhattan,Apartment,100.0,Entire home/apt,10004.0,1.0,1,9,250,100.0
7,2078,15/08/2008,"Colorful, quiet, & near the subway!",Brooklyn,Apartment,90.0,Private room,11201.0,1.0,1,80,90,94.0
8,2339,20/08/2008,East Village Cocoon: 2 Bedroom Flat,Manhattan,Apartment,90.0,Entire home/apt,10009.0,2.0,1,95,270,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30332,42349033,24/08/2015,Cute cozy studio in east village,Manhattan,Apartment,100.0,Entire home/apt,10003.0,1.0,1,1,90,100.0
30347,42430249,24/08/2015,Room in new spacious loft!,Brooklyn,Apartment,80.0,Private room,11222.0,1.0,1,1,65,80.0
30378,42518458,25/08/2015,Williamsburg Luxury Loft!??Bed Top,Brooklyn,Loft,100.0,Shared room,11206.0,1.0,1,1,55,100.0
30404,42697124,27/08/2015,"Cute, Clean Room- East Williamsburg",Brooklyn,Apartment,100.0,Private room,11206.0,1.0,1,1,60,100.0
30409,42726605,27/08/2015,Cozy and Near Tourist Attractions,Manhattan,Apartment,80.0,Private room,10002.0,1.0,1,1,99,80.0

***Como lo hacemos si queremos borrar solo los registros que tengan NaN en cierta columna?, eso lo haremos con el parametro subset, antes mencionado, de la siguiente manera:***

In [14]:
airbnb_no_beds = airbnb.dropna(subset=['Beds'])

In [15]:
airbnb_no_beds

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,26/06/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,26/06/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,43022976,31/08/2015,10 Mins to Time Square/two floors,Queens,Apartment,NaN,Entire home/apt,11101.0,5.0,1,0,300,NaN
30474,42993382,31/08/2015,"1BR ocean view & F,Q train st",Brooklyn,Apartment,NaN,Private room,11224.0,2.0,1,0,125,NaN
30475,43033067,31/08/2015,Amazing Private Room,Brooklyn,Other,NaN,Private room,11206.0,1.0,1,0,80,NaN
30476,43000991,31/08/2015,Charming private female room: UWS,Manhattan,Apartment,NaN,Private room,10025.0,1.0,1,0,35,NaN
30477,42999189,31/08/2015,Huge Beautiful Bedroom - Astoria,Queens,House,NaN,Private room,11105.0,1.0,1,0,80,NaN

## Metodos Unique & Nunique

**"unique()" nos permite mostrar en una lista, los valores unicos que aparecen en una columna (llamese una lista de los posibles valores que puede adquirir esa columna en los registros segun la info en el dataframe)** <br><br>

***Por ejemplo:***

In [16]:
airbnb['Neighbourhood'].unique()

array(['Brooklyn', 'Manhattan', 'Queens', 'Bronx', 'Staten Island'],
      dtype=object)

**Por otro lado esta "nunique()", que nos permite contar cuantos valores unicos hay**<br><br>

***Por ejemplo:***

In [17]:
airbnb['Neighbourhood'].nunique()

5

***IMPORTANTE: unique() considera los valores NaN, por lo que de no limpiar el dataset antes, estos seran conciderados en la lista, como podemos ver abajo***

In [18]:
airbnb['Beds'].unique()

array([ 1.,  3.,  2.,  4.,  5., nan,  6., 10.,  7.,  8., 12.,  0., 16.,
        9., 11.])

**IMPORTANTE: nunique(), por defecto, no cuenta los NaN, si los queremos considerar en el conteo, debemos especificarlo pasandole el parametro dropna, que utiliza un bool para activar o desactivar esta funcion** <br><br>

***Ejermplos para ambos casos:***

In [19]:
airbnb['Beds'].nunique() #No cuenta los NaN

14

In [20]:
airbnb['Beds'].nunique(dropna=False) #Cuenta los NaN, ya que estamos especificando que desactive la eliminacion de los mismos

15

## Filtrar data con metodo Between

**El metodo Between funciona similar a isna(), respondiendonos con un boolean si el valor en la columna cumple o no con el filtro que estamos dandole, en este caso between, que significa "entre"** <br><br>

***Por ejemplo: consultemos filtrando por precio del airbnb, para esto, usamos el metopdo between(), especificando dentro del parentesis entre que valores estaran los valores de precio de cada registro***

In [21]:
airbnb['Price'].between(100, 200) #Como se puede ver aqui estoy consultando si el valor de la columna price del registro esta entre 100 y 200

0         True
1        False
2        False
3         True
4        False
         ...
30473    False
30474     True
30475    False
30476    False
30477    False
Name: Price, Length: 30478, dtype: bool

<br>*Se ve algo feo, pero lo podemos arreglar con otro set de airbnb + corchetes* <br>

In [22]:
airbnb[airbnb['Price'].between(100, 200)] #Con este set extra de corchetes y nombre del dataframe veremos los resultados mas ordenados

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
3,500,26/06/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
5,1039,25/07/2008,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0
10,2571,27/08/2008,THE PUTNAM,Brooklyn,Apartment,95.0,Entire home/apt,11221.0,2.0,1,14,170,98.0
16,2965,14/09/2008,Large Bedroom in 3-bedroom Apt.,Manhattan,Apartment,95.0,Private room,10025.0,1.0,1,52,145,99.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30467,42995294,31/08/2015,"Colorful, comfortable artsy 2 bdrm",Brooklyn,Apartment,NaN,Entire home/apt,11238.0,3.0,1,0,127,NaN
30468,18223173,31/08/2015,Lovely East Village Apartment,Manhattan,Apartment,NaN,Entire home/apt,10009.0,1.0,1,0,195,NaN
30469,43018396,31/08/2015,Cute East Village Studio Sept 8-16,Manhattan,Apartment,NaN,Entire home/apt,10009.0,1.0,1,0,105,NaN
30471,42959506,31/08/2015,Time Square! 2 Fully Furnished apt.,Manhattan,Apartment,NaN,Entire home/apt,10036.0,2.0,1,0,200,NaN
30474,42993382,31/08/2015,"1BR ocean view & F,Q train st",Brooklyn,Apartment,NaN,Private room,11224.0,2.0,1,0,125,NaN

**Como se puede comprobar arriba, esta vez, el resultado nos trajo solo los registros con un precio de entre 100 y 200 USD**<br><br>

**A este metodo podemos agregar el metodo value_counts(), de modo que podamos contar cuantos registros hay de cada valor unico en la columna**<br><br>

***Por ejemplo***

In [23]:
airbnb[airbnb['Price'].between(100, 200)]['Price'].value_counts()

Price
150    1481
100    1207
200    1059
125     889
120     743
       ...
176       4
191       4
193       3
183       3
181       3
Name: count, Length: 101, dtype: int64

## Utilizando multiples filtros

Para utilizar varios filtro podemos usar el simbolo and "&"

In [24]:
airbnb[airbnb['Price'].between(100, 200) & airbnb['Beds'].between(1,2)]

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
5,1039,25/07/2008,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0
10,2571,27/08/2008,THE PUTNAM,Brooklyn,Apartment,95.0,Entire home/apt,11221.0,2.0,1,14,170,98.0
16,2965,14/09/2008,Large Bedroom in 3-bedroom Apt.,Manhattan,Apartment,95.0,Private room,10025.0,1.0,1,52,145,99.0
17,3211,25/09/2008,"Elegant NYC, 10mins to Manhattan!",Queens,Apartment,90.0,Private room,11106.0,1.0,1,3,100,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30466,42997784,31/08/2015,Beautiful parkfront sanctuary,Brooklyn,Apartment,NaN,Entire home/apt,11226.0,1.0,1,0,160,NaN
30468,18223173,31/08/2015,Lovely East Village Apartment,Manhattan,Apartment,NaN,Entire home/apt,10009.0,1.0,1,0,195,NaN
30469,43018396,31/08/2015,Cute East Village Studio Sept 8-16,Manhattan,Apartment,NaN,Entire home/apt,10009.0,1.0,1,0,105,NaN
30471,42959506,31/08/2015,Time Square! 2 Fully Furnished apt.,Manhattan,Apartment,NaN,Entire home/apt,10036.0,2.0,1,0,200,NaN
30474,42993382,31/08/2015,"1BR ocean view & F,Q train st",Brooklyn,Apartment,NaN,Private room,11224.0,2.0,1,0,125,NaN

**Ademas de usar Between, podemos tambien usar valores iguales con "==".**<br><br>

***Por ejemplo:***

In [25]:
airbnb[airbnb['Price'].between(100, 200) & airbnb['Beds'] == 1]

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
3,500,26/06/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
5,1039,25/07/2008,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0
10,2571,27/08/2008,THE PUTNAM,Brooklyn,Apartment,95.0,Entire home/apt,11221.0,2.0,1,14,170,98.0
16,2965,14/09/2008,Large Bedroom in 3-bedroom Apt.,Manhattan,Apartment,95.0,Private room,10025.0,1.0,1,52,145,99.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30467,42995294,31/08/2015,"Colorful, comfortable artsy 2 bdrm",Brooklyn,Apartment,NaN,Entire home/apt,11238.0,3.0,1,0,127,NaN
30468,18223173,31/08/2015,Lovely East Village Apartment,Manhattan,Apartment,NaN,Entire home/apt,10009.0,1.0,1,0,195,NaN
30469,43018396,31/08/2015,Cute East Village Studio Sept 8-16,Manhattan,Apartment,NaN,Entire home/apt,10009.0,1.0,1,0,105,NaN
30471,42959506,31/08/2015,Time Square! 2 Fully Furnished apt.,Manhattan,Apartment,NaN,Entire home/apt,10036.0,2.0,1,0,200,NaN
30474,42993382,31/08/2015,"1BR ocean view & F,Q train st",Brooklyn,Apartment,NaN,Private room,11224.0,2.0,1,0,125,NaN

***Otro ejemplo:***

In [26]:
airbnb[(airbnb['Property Type'] == 'Apartment') & (airbnb['Neighbourhood'] == 'Manhattan')]

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,26/06/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,26/06/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0
6,1783,12/08/2008,Amazing Also,Manhattan,Apartment,100.0,Entire home/apt,10004.0,1.0,1,9,250,100.0
8,2339,20/08/2008,East Village Cocoon: 2 Bedroom Flat,Manhattan,Apartment,90.0,Entire home/apt,10009.0,2.0,1,95,270,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30469,43018396,31/08/2015,Cute East Village Studio Sept 8-16,Manhattan,Apartment,NaN,Entire home/apt,10009.0,1.0,1,0,105,NaN
30470,42991892,31/08/2015,Upper West Side Luxury Apartment,Manhattan,Apartment,NaN,Entire home/apt,10023.0,1.0,1,0,240,NaN
30471,42959506,31/08/2015,Time Square! 2 Fully Furnished apt.,Manhattan,Apartment,NaN,Entire home/apt,10036.0,2.0,1,0,200,NaN
30472,43007478,31/08/2015,Luxury apt with spectacular views,Manhattan,Apartment,NaN,Entire home/apt,10036.0,2.0,1,0,850,NaN
30476,43000991,31/08/2015,Charming private female room: UWS,Manhattan,Apartment,NaN,Private room,10025.0,1.0,1,0,35,NaN

**IMPORTANTE:**<BR><BR>
En Python:

() → paréntesis → agrupan expresiones

[] → indexación (acceder a algo)

& → operador lógico AND (bit a bit)


Los corchetes NO sirven para agrupar condiciones, solo para indexar.
<br><br>
Por eso los filtros o condiciones van en parentesis simple y no corchete o llaves

**Podemos agregar cuantas condiciones queramos usando &**

## Filtros avanzados con Isin y Or (representado por el simpbolo "|")

In [27]:
salaries

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,EX,FT,Data Science Director,212000,USD,212000,US,0,US,M
1,2023,EX,FT,Data Science Director,190000,USD,190000,US,0,US,M
2,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
3,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
4,2023,SE,FT,Machine Learning Engineer,245700,USD,245700,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
8800,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
8801,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
8802,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
8803,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
8804,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

***Digamos que deseo filtrar de este dataframe solo los registros que tenga como titulo universitario Data engineer y Data Scientist, para esto podemos usar or***<br><br>

***Por ejemplo:***

In [28]:
salaries[(salaries['job_title'] == 'Data Scientist') | (salaries['job_title'] == 'Data Engineer')]

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
10,2023,MI,FT,Data Scientist,212000,USD,212000,US,0,US,M
11,2023,MI,FT,Data Scientist,93300,USD,93300,US,0,US,M
14,2023,MI,FT,Data Engineer,133000,USD,133000,US,0,US,M
15,2023,MI,FT,Data Engineer,58300,USD,58300,US,0,US,M
18,2023,SE,FT,Data Engineer,300000,USD,300000,US,100,US,M
...,...,...,...,...,...,...,...,...,...,...,...
8793,2020,MI,FT,Data Engineer,130800,USD,130800,ES,100,US,M
8796,2021,MI,FT,Data Scientist,160000,SGD,119059,SG,100,IL,M
8798,2021,MI,FT,Data Engineer,24000,EUR,28369,MT,50,MT,L
8800,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
8802,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S

**Incluso podemos meterle un and a alguna de las condiciones** <br><br>

***Por ejemplo:***

In [29]:
salaries[((salaries['job_title'] == 'Data Scientist') & (salaries['salary_in_usd'] == 212000)) | 
    ((salaries['job_title'] == 'Data Engineer') & (salaries['salary_in_usd'] == 300000))] 
#Estas dos lineas de codigo se pueden poner en una, pero se ve mas ordenado en dos a mi gusto

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
10,2023,MI,FT,Data Scientist,212000,USD,212000,US,0,US,M
18,2023,SE,FT,Data Engineer,300000,USD,300000,US,100,US,M
66,2023,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
300,2023,MI,FT,Data Scientist,212000,USD,212000,US,0,US,M
312,2023,SE,FT,Data Scientist,212000,USD,212000,US,0,US,M
343,2023,SE,FT,Data Scientist,212000,USD,212000,US,0,US,M
427,2023,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
1259,2023,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
2765,2023,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
6552,2023,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
6684,2023,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
7246,2022,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
7583,2022,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
7749,2022,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
7931,2022,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M

**De querer contar los resultados que hacen match, tambien se puede hacer, mediante value_counts()**<br><br> 
***Por ejemplo:***

In [30]:
salaries[((salaries['job_title'] == 'Data Scientist') & (salaries['salary_in_usd'] == 212000)) | 
    ((salaries['job_title'] == 'Data Engineer') & (salaries['salary_in_usd'] == 300000))]['job_title'].value_counts()

job_title
Data Engineer     11
Data Scientist     4
Name: count, dtype: int64

**Otra forma de filtrar es con el metodo "isin()", el cual usaremos de la siguiente manera:**

In [31]:
salaries[
    (salaries['job_title'].isin(['Data Scientist','Data Engineer'])) & 
    (salaries['salary_in_usd'] > 212000)
    ]

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
18,2023,SE,FT,Data Engineer,300000,USD,300000,US,100,US,M
28,2023,SE,FT,Data Scientist,236160,USD,236160,US,100,US,M
42,2023,SE,FT,Data Scientist,258000,USD,258000,US,0,US,M
64,2023,SE,FT,Data Scientist,231250,USD,231250,US,0,US,M
66,2023,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
8464,2022,SE,FT,Data Scientist,230000,USD,230000,US,100,US,M
8468,2022,SE,FT,Data Scientist,220000,USD,220000,US,100,US,M
8478,2022,EX,FT,Data Engineer,324000,USD,324000,US,100,US,M
8479,2022,EX,FT,Data Engineer,216000,USD,216000,US,100,US,M
8800,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L

In [32]:
salaries[
    (salaries['job_title'].isin(['Data Scientist','Data Engineer'])) & 
    (salaries['salary_in_usd'] > 212000)
    ]

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
18,2023,SE,FT,Data Engineer,300000,USD,300000,US,100,US,M
28,2023,SE,FT,Data Scientist,236160,USD,236160,US,100,US,M
42,2023,SE,FT,Data Scientist,258000,USD,258000,US,0,US,M
64,2023,SE,FT,Data Scientist,231250,USD,231250,US,0,US,M
66,2023,SE,FT,Data Engineer,300000,USD,300000,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
8464,2022,SE,FT,Data Scientist,230000,USD,230000,US,100,US,M
8468,2022,SE,FT,Data Scientist,220000,USD,220000,US,100,US,M
8478,2022,EX,FT,Data Engineer,324000,USD,324000,US,100,US,M
8479,2022,EX,FT,Data Engineer,216000,USD,216000,US,100,US,M
8800,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L

**Igual que antes, añadiremos un value_counts(), para contar los resultados**

In [33]:
salaries[
    (salaries['job_title'].isin(['Data Scientist','Data Engineer'])) & 
    (salaries['salary_in_usd'] > 212000)
    ]['job_title'].value_counts()

job_title
Data Scientist    282
Data Engineer     272
Name: count, dtype: int64

## Operador tilde (~) para la negación bit a bit

**En pandas, ~ es el operador de NEGACIÓN lógica y equivale a decir NOT.**<br><br>

**Este se usa para identificar todos los valore que NO cumplen con los filtros presentados**<br><br>

***Por ejemplo:***

In [34]:
salaries[~(salaries['job_title'].isin(['Data Scientist','Data Engineer']))] 
#Aqui estamos excluyendo los titulos que sean Data Engineer y Data Scientist

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,EX,FT,Data Science Director,212000,USD,212000,US,0,US,M
1,2023,EX,FT,Data Science Director,190000,USD,190000,US,0,US,M
2,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
3,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
4,2023,SE,FT,Machine Learning Engineer,245700,USD,245700,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
8797,2021,MI,FT,Applied Machine Learning Scientist,423000,USD,423000,US,50,US,L
8799,2021,SE,FT,Data Specialist,165000,USD,165000,US,100,US,L
8801,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
8803,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
8804,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

**Podemos usar este tile "~" para negar varias condicione tambien**<br><br>
***Por ejemplo:***

In [35]:
salaries[
    (~(salaries['job_title'].isin(['Data Scientist','Data Engineer']))) &
    (~(salaries['experience_level'] == 'SE'))
    ] 
#Aqui estamos diciendo que nos busque todos aquellos registros que no sean ni Data Engineer ni Data Scientist y 
#todos los que no tengan nivel de experiencia SE

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,EX,FT,Data Science Director,212000,USD,212000,US,0,US,M
1,2023,EX,FT,Data Science Director,190000,USD,190000,US,0,US,M
2,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
3,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
6,2023,MI,FT,Data Specialist,90000,USD,90000,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
8786,2021,MI,FT,Data Analyst,75000,USD,75000,US,0,US,L
8787,2021,MI,FT,Data Analyst,62000,USD,62000,US,0,US,L
8797,2021,MI,FT,Applied Machine Learning Scientist,423000,USD,423000,US,50,US,L
8801,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
8803,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L

In [36]:
salaries[
    ~(
        (salaries['job_title'] == 'Data Scientist') &
        (salaries['experience_level'] == 'SE')
     )
]
#Aqui por ejemplo, le estamos diciendo que ignore todos los registros que tengan titulo Data Scientist y ademas nivel SE en ese cargo

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,EX,FT,Data Science Director,212000,USD,212000,US,0,US,M
1,2023,EX,FT,Data Science Director,190000,USD,190000,US,0,US,M
2,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
3,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
4,2023,SE,FT,Machine Learning Engineer,245700,USD,245700,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
8799,2021,SE,FT,Data Specialist,165000,USD,165000,US,100,US,L
8801,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
8802,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
8803,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
8804,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

## Crear y Eliminar columnas

**Para crear una nueva columna, solo debemos escribir el nombre de la variable con nuestro DataFrame, seguido de corchetes y dentro de los mismos entre comillas simples el nombre de la columna, ya por ultimo, debemos agregar un igual y el valor que ocupara esa columna.**<br><br>

***Por ejemplo:***

In [50]:
airbnb['City'] = 'New York'

In [38]:
airbnb

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating,City
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN,New York
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN,New York
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN,New York
3,500,26/06/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN,New York
4,500,26/06/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0,New York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,43022976,31/08/2015,10 Mins to Time Square/two floors,Queens,Apartment,NaN,Entire home/apt,11101.0,5.0,1,0,300,NaN,New York
30474,42993382,31/08/2015,"1BR ocean view & F,Q train st",Brooklyn,Apartment,NaN,Private room,11224.0,2.0,1,0,125,NaN,New York
30475,43033067,31/08/2015,Amazing Private Room,Brooklyn,Other,NaN,Private room,11206.0,1.0,1,0,80,NaN,New York
30476,43000991,31/08/2015,Charming private female room: UWS,Manhattan,Apartment,NaN,Private room,10025.0,1.0,1,0,35,NaN,New York
30477,42999189,31/08/2015,Huge Beautiful Bedroom - Astoria,Queens,House,NaN,Private room,11105.0,1.0,1,0,80,NaN,New York

**Por otro lado, para eliminar columnas usamos el metodo drop(), especificando entre parentesis la o las columna(s) a borrar**<br><br>

***Por Ejemplo:***

In [48]:
airbnb.drop(columns = 'City', inplace = True) #Podemos guardar el resultado en una variable, o usar inplace para mantener los cambios

In [49]:
airbnb

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,26/06/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,26/06/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,43022976,31/08/2015,10 Mins to Time Square/two floors,Queens,Apartment,NaN,Entire home/apt,11101.0,5.0,1,0,300,NaN
30474,42993382,31/08/2015,"1BR ocean view & F,Q train st",Brooklyn,Apartment,NaN,Private room,11224.0,2.0,1,0,125,NaN
30475,43033067,31/08/2015,Amazing Private Room,Brooklyn,Other,NaN,Private room,11206.0,1.0,1,0,80,NaN
30476,43000991,31/08/2015,Charming private female room: UWS,Manhattan,Apartment,NaN,Private room,10025.0,1.0,1,0,35,NaN
30477,42999189,31/08/2015,Huge Beautiful Bedroom - Astoria,Queens,House,NaN,Private room,11105.0,1.0,1,0,80,NaN

**Otra opcion para hacer lo mismo, es usando drop con los parametros labels y axis**<br><br>

***Ejemplo:***<br>

airbnb.drop(labels = 'City', axis=1)<br> 

**En este caso tambien podemos usar inplace para guardar los cambios en el dataframe**<br><br>

**IMPORTANTE:** <br><br>

***El valor que toma el parametro axis, dependera de si quieres borrar filas o columnas, por defecto, el metodo tiene el parametro axis en 0 (filas), el parametro se debe poner en 1 si se quiere dropear una columna.*** <br><br>

axis=0  → filas (vertical)<br>
axis=1  → columnas (horizontal)
<br><br>
**axis = 0 (default):**
- Trabaja a lo largo de las filas
- Operas columna por columna

**Se usa para:**
- Borrar filas
- Calcular estadísticas por columna

**axis = 1:**
- Trabaja a lo largo de las columnas
- Operas fila por fila

**Se usa para:**
- Borrar columnas
- Cálculos por fila

## Creando Columnas Dinamicas

**Para crear columans dinamicas, se hace igual que con columnas normales, pero se cambia lo que va despues del = por formulas**<br><br>
***Por ejemplo:***

In [57]:
sales['Sales + Tax'] = sales['SalesAmount'] + sales['TaxAmt']

In [59]:
sales

,ProductKey,product,product_subcategory,OrderDateKey,CalendarYear,SalesTerritoryRegion,SalesTerritoryCountry,SalesOrderNumber,SalesAmount,TaxAmt,Freight,Sales + Tax
0,310,"Road-150 Red, 62",Road Bikes,20101229,2010,Canada,Canada,SO43697,3578.2700,286.2616,89.4568,3864.5316
1,346,"Mountain-100 Silver, 44",Mountain Bikes,20101229,2010,France,France,SO43698,3399.9900,271.9992,84.9998,3671.9892
2,346,"Mountain-100 Silver, 44",Mountain Bikes,20101229,2010,Northwest,United States,SO43699,3399.9900,271.9992,84.9998,3671.9892
3,336,"Road-650 Black, 62",Road Bikes,20101229,2010,Southwest,United States,SO43700,699.0982,55.9279,17.4775,755.0261
4,346,"Mountain-100 Silver, 44",Mountain Bikes,20101229,2010,Australia,Australia,SO43701,3399.9900,271.9992,84.9998,3671.9892
...,...,...,...,...,...,...,...,...,...,...,...,...
60393,485,Fender Set - Mountain,Fenders,20140128,2014,Canada,Canada,SO75122,21.9800,1.7584,0.5495,23.7384
60394,225,AWC Logo Cap,Caps,20140128,2014,Canada,Canada,SO75122,8.9900,0.7192,0.2248,9.7092
60395,485,Fender Set - Mountain,Fenders,20140128,2014,Canada,Canada,SO75123,21.9800,1.7584,0.5495,23.7384
60396,486,All-Purpose Bike Stand,Bike Stands,20140128,2014,Canada,Canada,SO75123,159.0000,12.7200,3.9750,171.7200
60397,225,AWC Logo Cap,Caps,20140128,2014,Canada,Canada,SO75123,8.9900,0.7192,0.2248,9.7092

***Nota: al igual que en python nativo (sin librerias extra), puedes usar el + para concatenar***<br><br>
**Por ejemplo:**

sales['sales type'] = sales['product_subcategory'] + ' ' + sales['SalesTerritoryCountry']